CREATE TABLE profiles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_sub VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) DEFAULT '',
    phone VARCHAR(20) DEFAULT '',
    avatar_url VARCHAR(500) DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_user_sub (user_sub)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
